version: "3"

dotenv: ['.env']

env:
  DEFAULT_TITLE: Whiskey and Smokes
  DEFAULT_REGION: "eastus2"

includes:
  test:
    taskfile: ./tasks/Taskfile.test.yml
    internal: false
    dir: .

  local:
    taskfile: ./tasks/Taskfile.local.yml
    internal: false
    dir: ./infrastructure/local/

  azure:
    taskfile: ./tasks/Taskfile.azure.yml
    internal: false
    dir: ./infrastructure/azure/

  azure:app:
    taskfile: ./tasks/Taskfile.azure.deploy.yml
    internal: false
    dir: ./tasks

tasks:
  default:
    cmds:
      - task --list