version: "3"

dotenv: ['.env']

env:
  DEFAULT_TITLE: Whiskey and Smokes
  DEFAULT_REGION: "eastus2"

includes:
  app:
    taskfile: ./tasks/Taskfile.app.yml
    internal: false
    dir: .

  local:
    taskfile: ./tasks/Taskfile.local.yml
    internal: false
    dir: ./infrastructure/local/

  azure:
    taskfile: ./tasks/Taskfile.azure.yml
    internal: false
    dir: ./infrastructure/azure/

  deploy:
    taskfile: ./tasks/Taskfile.deploy.yml
    internal: false
    dir: .

tasks:
  default:
    cmds:
      - task --list