version: "3"

vars:
  TITLE: Whiskey & Smokes (local)
  DEFAULT_REGION: eastus2

tasks:
  default:
    cmds:
      - task --list

  up:
    desc: Provisions Azure AI Foundry resources for {{.TITLE}}
    cmds:
      - terraform workspace new {{.REGION}} || true
      - terraform workspace select {{.REGION}}
      - terraform init
      - task: apply
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  apply:
    desc: Applies Terraform configuration for {{.TITLE}}
    cmds:
      - terraform apply -auto-approve -compact-warnings
        -var "region={{.REGION}}"
        -var "tags={{.TITLE}}"
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  agents:
    desc: Validates agent configuration against AI Foundry
    env:
      AiFoundry__ProjectEndpoint: "{{.PROJECT_ENDPOINT}}"
    cmds:
      - dotnet run --project ../../src/AgentInitiator
    # vars:
    #   PROJECT_ENDPOINT: https://poodle-63974-foundry.services.ai.azure.com/api/projects/poodle-63974-project
    #     #sh: terraform output -raw FOUNDRY_PROJECT_ENDPOINT 2>/dev/null || echo ""

  output:
    desc: Shows Terraform outputs for {{.TITLE}}
    cmds:
      - terraform output

  down:
    desc: Destroys all resources and cleans up Terraform for {{.TITLE}}
    cmds:
      - terraform destroy -auto-approve 
        -var "region={{.REGION}}"
        -var "tags={{.TITLE}}" || true
      - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true     
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"